apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.AppName }}-mariadb-config
  namespace: {{ .Values.NameSpace }}
data:
  my.cnf: |
    [mysqld]
    server-id = {{ .Values.MariadbServerId }}
    replicate-do-db = {{ .Values.MariadbDbName }}