apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.AppName }}-mariadb-service
  namespace: {{ .Values.NameSpace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.AppName }}-mariadb
  ports:
  - port: {{ .Values.MariadbDbPort }}
    targetPort: {{ .Values.MariadbDbPort }}
    protocol: TCP
    nodePort: {{ .Values.NodePort }}  # Un port dans la plage 30000-32767